services:
  - type: web
    name: e-arogyata-hospital-platform
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
